# Generated by Django 3.0.6 on 2020-08-28 19:09

import dialogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('chatPhoto', models.TextField(default="{'small' : null, 'large' : null}")),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorOfConversations', to='snusers.SNUser')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationForSNUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastReadMessageId', models.IntegerField(default=0)),
                ('startMsgId', models.IntegerField(default=0)),
                ('chatTypeId', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('isAdmin', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snusers', to='dialogs.Conversation')),
                ('snuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='snusers.SNUser')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dialogs.models.CastableModelMixin),
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DialogForSNUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastReadMessageId', models.IntegerField(default=0)),
                ('startMsgId', models.IntegerField(default=0)),
                ('chatTypeId', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snusers', to='dialogs.Dialog')),
                ('snuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='snusers.SNUser')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dialogs.models.CastableModelMixin),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('name', models.CharField(max_length=300)),
                ('format', models.CharField(max_length=300)),
                ('isImage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyDialogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField()),
                ('sended', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('snuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.DialogForSNUser')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dialogs.models.CastableModelMixin),
        ),
        migrations.CreateModel(
            name='MyConversationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField()),
                ('sended', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('snuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.ConversationForSNUser')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dialogs.models.CastableModelMixin),
        ),
        migrations.CreateModel(
            name='DialogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField()),
                ('sended', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='globalDialogs', to='snusers.SNUser')),
                ('localMessage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='globalMsg', to='dialogs.MyDialogMessage')),
                ('snuserGlobal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.Dialog')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dialogs.models.CastableModelMixin),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField()),
                ('sended', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='globalConversations', to='snusers.SNUser')),
                ('localMessage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='globalMsg', to='dialogs.MyConversationMessage')),
                ('snuserGlobal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.Conversation')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, dialogs.models.CastableModelMixin),
        ),
    ]
